name: text_link
description: This Flutter package is designed to simplify text rendering with embedded URLs. It allows users to tap on any URL in the text (even at the beginning, end, or if the URL format is incorrect) to open the link.
version: 0.0.2


environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11

flutter:
  plugin:
    platforms:
      android:
        package: com.void.textlink
        pluginClass: LinktextPlugin
      ios:
        package: com.void.textlink
        pluginClass: LinktextPlugin


