name: text_link
description: This Flutter package simplifies text rendering with embedded URLs, enabling users to tap on any URL within the text to open the link.
version: 1.0.0
homepage: https://github.com/safeenkurd/LinkText/blob/main/example/lib/main.dart
repository: https://github.com/safeenkurd/LinkText/blob/main/

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true

